### ISSUE TITLE
Stopped working with after version Wiki.js 2.5.289

### ISSUE THREAD

**Issue by smilebasti** [requarks/wiki-update-companion#2]
Hi,

i used to update my wiki.js instance with the integrated button which uses this app since half a year.
Now i checked back in to update again but it doesn't update anymore. I am on version Wiki.js 2.5.289.

When i press the update button the dialog says: Your wiki.js container is being updated. The prgogress bar runs through and at the end the site refreshes but i am still on Wiki.js 2.5.289. Then i am able to preform the upgrade again.

Any thoughts would this could be?

The following repeats in the wiki-companion-app logs:
```
Unhandled exception. Docker.DotNet.DockerApiException: Docker API responded with status code=BadRequest, response=400 Bad Request
   at Docker.DotNet.DockerClient.HandleIfErrorResponseAsync(HttpStatusCode statusCode, HttpResponseMessage response, IEnumerable`1 handlers)
   at Docker.DotNet.DockerClient.MakeRequestForStreamAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
   at Docker.DotNet.Models.StreamUtil.MonitorStreamForMessagesAsync[T](Task`1 streamTask, DockerClient client, CancellationToken cancel, IProgress`1 progress)
   at wiki_update_companion.Controllers.UpgradeController.Post() in /src/Controllers/UpgradeController.cs:line 44
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
```

Thanks ahead

**Comment by smilebasti** [comment]
I fixed it by removing the container and recreating it.
